//
//  AppDelegate.m
//  myFirstIOSApp
//
//  Created by Noah Cabral on 2022-02-06.
//

#import "AppDelegate.h"

@interface AppDelegate ()

@end

@implementation AppDelegate


// In objective-C, the method declaration syntax is REALLY wierd. The names of functions are generated by the names
// of the parameters, but also parameters are not named...
// The name of the function below is application:didFinishLaunchingWithOptions:
// See https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/DefiningClasses/DefiningClasses.html#:~:text=An%20Objective%2DC%20method%20declaration,a%20standard%20C%20type%2Dcast.
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    return YES;
}


#pragma mark - UISceneSession lifecycle


- (UISceneConfiguration *)application:(UIApplication *)application configurationForConnectingSceneSession:(UISceneSession *)connectingSceneSession options:(UISceneConnectionOptions *)options {
    // Called when a new scene session is being created.
    // Use this method to select a configuration to create the new scene with.
    return [[UISceneConfiguration alloc] initWithName:@"Default Configuration" sessionRole:connectingSceneSession.role];
}


- (void)application:(UIApplication *)application didDiscardSceneSessions:(NSSet<UISceneSession *> *)sceneSessions {
    // Called when the user discards a scene session.
    // If any sessions were discarded while the application was not running, this will be called shortly after application:didFinishLaunchingWithOptions.
    // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
}


@end
