// NOTE(NOAH): Pointers not here yet, so char **argv is going to have to wait...
int main(int argc, char argv) {
    for (int i = 0; i < argc; i = i + 1)
        printf("parameter %s", argv); // Also note the lack of [] operator...
}