name: Windows build 
on:
  push:
    branches:    
      - 'master'

jobs:
  build-test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - name: Install Visual Studio 
        uses: ilammy/msvc-dev-cmd@v1
        with: 
          arch: x64
      - name: Setup
        shell: bash
        run: rm /usr/bin/link
      - name: Preparser Test
        run: ./build.bat pall 
        shell: bash
      - name: Grammar Test
        run: ./build.bat gall 
        shell: bash
      
      - name: Backend Tests
        run: ./build.bat wax64all
