on:
  push:
    branches:    
      - 'master'

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Build PPL
        run: ./build.sh b 
        shell: bash
      - name: Preparser Test
        run: ./build.sh pall 
        shell: bash
      - name: Grammer Test
        run: ./build.sh gall 
        shell: bash