name: macOS build
on:
  push:
    branches:    
      - 'master'

jobs:
  build-test-ubuntu:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - name: Build PPL
        run: ./build.sh b 
        shell: bash
      - name: Preparser Test
        run: ./build.sh pall 
        shell: bash
      - name: Grammer Test
        run: ./build.sh gall 
        shell: bash
      - name: Backend Tests
        shell: bash
        run: ./build.sh ax64all